### ISSUE TITLE
Getting API last error

### ISSUE THREAD

**Issue by BenJaziaSadok** [CpuID/pve2-api-php-client#25]
Hello, 
I want to get the last error when using the API call.
Are there a way to do this?

**Comment by naja7host** [comment]
the class send the output error to the log , so the option is not possible with the actual class .

**Comment by danhunsaker** [comment]
This is likely to change very soon.  I'm planning to implement PSR-3 support in the next week or so.

**Comment by didiandalucia** [comment]
But a little bit change in the documentation, will help us too!

**Comment by BenJaziaSadok** [comment]
I have fixed that by changing this line from error_log to echo [ligne](https://github.com/CpuID/pve2-api-php-client/blob/master/pve2_api.class.php#L252) and changed to display that in every http request, not only PUT.
I can make a PR if you want.

**Comment by danhunsaker** [comment]
I never got around to the PSR-3 conversion, as I'm sure you've noticed.  Would much prefer a PR with that over one that calls `echo` - that's actually worse than only supporting `error_log()`, because it would pollute existing users' output.  A fallback Logger that sends messages to the standard error log would also be preferable for BC reasons.
