### ISSUE TITLE
 Login to Proxmox Host failed. 

### ISSUE THREAD

**Issue by Kippenbeer** [CpuID/pve2-api-php-client#32]
I'm 100% sure all the details are correct but i keep getting Login to Proxmox Host failed.

**Comment by danhunsaker** [comment]
What version of PVE are you running?

**Comment by Kippenbeer** [comment]
Proxmox Virtual Environment 5.1-41?

**Comment by danhunsaker** [comment]
Ok, I'll investigate that. This library was written around PVE 3, so some things may have changed a bit since then, and we may need to adjust the code accordingly.

**Comment by Kippenbeer** [comment]
Okay thanks. When I was in the data center was it worked though. Since I'm at home anymore, I have not changed the code.

Via Postman, I tried to create a ticket by a postal mail. This does work. Lets make I the login function after.

Sorry for my bad English.

- Kippenbeer

**Comment by emresaracoglu** [comment]
Virtual Environment 5.4-13
The connection does not occur.

**Comment by spamhome** [comment]
https://github.com/CpuID/pve2-api-php-client/pull/36

**Comment by lucapiccio** [comment]
Hi, i'm debugging with Proxmox VE 7.2

after an analysis, i've found the problem is simply that 
`setrawcookie("PVEAuthCookie", $this->login_ticket['ticket'], 0, "/");`
is setting cookie for the actual domain, not for the public url of the PVE

You can try with somthing similar :
`setrawcookie("PVEAuthCookie", $this->login_ticket['ticket'], 0, "/", $this->hostname,true,false);`

but the problem is that the browsers doesn't allow to set cookie for other domains. 

I've solved this and i'm writing a patched version but this is "almost" the solution but i dont like that the cookie allow also to login to 8006 interface. I think is better to connect a Vnc client to the PVE vncproxy

**Comment by lsthompson** [comment]
Closing off this 5-6 y.o. discussion now. Improved error logging is in the works in Pull #42 - feel free to contribute.

re: @lucapiccio comments about anti-CSRF protections etc, yes, and in PVE v8.0 onwards this is mandatory now.

> Set strict SameSite attribute on the Authorization cookie ([ref](https://pve.proxmox.com/wiki/Roadmap))
