### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by evrifaessa** [CpuID/pve2-api-php-client#39]
Hey, thanks for the great project! We're planning to use the library on our project ([FOSSBilling](https://fossbilling.org), a fork of BoxBilling made by the latest team) but noticed the library hasn't received any updates recently.

Is there any chance of it receiving updates in the future, or are we completely out of luck?

We also are planning to contribute upstream from time to time. But if you aren't planning to maintain the project it will not be of much use.

We will be looking forward for your reply. For quicker communication, here is our [Discord server](https://fossbilling.org/discord). Have a nice day.

**Comment by CpuID** [comment]
hey @evrifaessa you're welcome :)

re updates - I wrote it initially back in 2012 for a specific project I was assigned to, and after moving on didn't have the time to add much to it. I mostly dived into using other languages also, although this library in PHP still has it's place 👍 

@danhunsaker approached me in 2014 re adding some new functionality which did make it in, but other than some minor user contributions that's about the only maintenance it's had since.

I likely don't have the free cycles to add much new code to it, but of course external contributions are always welcomed and I'm happy to review PR's as they come in etc. I haven't had any running Proxmox hosts that I admin for a while now to allow me to test this client against it, although that may change in the near future...
